### PR TITLE
MergeVar content attribute is now an object

### LINKED ISSUE #51: MergeVar Content attribute should be an object
@rschreijer MergeVar Content attribute should be of type Object so in this way i could insert different objects in order to create generic templates and add more complexity to them.

I think this is an issue because if i use gson to convert, lets say, a map and set it to a merge var, the api will parse that string again encoding the map and leaving it useless:

ex:

at my code:                              "{"key":"value"}"
second time in the api side:     "{\"key\":\"value\"}"

### PR DESCRIPTION
**Pull request by nwolff**
fixes #51 

This is needed to pass complex object or arrays to handlebar templates:
http://blog.mandrill.com/handlebars-for-templates-and-dynamic-content.html

@rschreijer please tell me if you want me to add unit tests before accepting to merge the PR

### CODE REVIEW

**Comment by diegoacuna** [comment]
@nwolff I recently fork this repo because it seems that the original repo is not mantained anymore. Anyways, I forked the repo and I'm merging all the pending (and useful) pull request from this repo. Your PR seems really useful, can you add the unit tests for your modification? (My intention is to bring this repo back to life in my fork)

**Comment by billoneil** [comment]
@diegoacuna I just got access to the repo and will begin merging some PRs over the next few days

**Comment by irufus** [comment]
This is great news

**Comment by billoneil** [comment]
fixes #50

**Comment by diegoacuna** [comment]
Awesome, I think after the merge, performing the update on the maven repo is also an essential task, @billoneil  do you have access to do this task too?

**Comment by billoneil** [comment]
I do not have access but I can make sure a new version gets released.  I want to go through some more issues and make release notes then I can get it done.  Might be a couple days.

**Comment by rschreijer** [comment]
I will make a new release and push it to maven central once @billoneil tells me to. You can expect a new release soon.

**Comment by gurghet** [comment]
I expect soon to be within 1 day >:(

**Comment by gurghet** [comment]
Thanks!

**Comment by kamwo** [comment]
Thanks guys!

**Comment by billoneil** [comment]
This seems fine without a unit test for now.

**Comment by Ruudieboy** [comment]
Awesome!

**Comment by rschreijer** [comment]
Snapshot: https://oss.sonatype.org/content/repositories/snapshots/com/mandrillapp/wrapper/lutung/lutung/0.0.6-SNAPSHOT/

release coming tonite.

**Pull request merged**
