### PR TITLE
Changeable Api address

### PR DESCRIPTION
**Pull request by sarpk**
Please see: https://github.com/rschreijer/lutung/issues/38

### CODE REVIEW

**Comment by billoneil** [comment]
Why would you need to proxy the entire api?  Testing can be handled with multiple API keys and/or test api keys.

**Comment by rschreijer** [comment]
@sarpk I also hesitate considering this way of using a proxy. Do you still need it?

Can we maybe find a way to implement this by configuring the proxy in the http client:
```
HttpHost proxy = new HttpHost("ip address",port number);
DefaultHttpClient httpclient = new DefaultHttpClient();
httpclient.getParams().setParameter(ConnRoutePNames.DEFAULT_PROXY,proxy);
```

**Comment by sarpk** [comment]
I am so sorry, it's been a year since I was working on it (I thought this repo was dead, in fact in my old company we forked and continued working on it, feel free to add anything from there if you want https://github.com/wotifgroup/lutung )

If I remember it right, the reason why I wanted to add proxy the entire API so that I can test the application rather than the API with acceptance testing and stubbing.

**Comment by rschreijer** [comment]
My bad. Thanks for contributing.

**Pull request closed without merging**
