### PR TITLE
Add support for specifying merge language (mailchimp or handlebars)

### PR DESCRIPTION
**Pull request by eweatherley**

### CODE REVIEW

**Comment by JoshEllinger** [comment]
@rschreijer can you pull this request in (or review). This would be super helpful to many users who are handcuffed by the current constraints of the mailchimp templating language.

**Comment by dudevon** [comment]
+1 for this pull request. I've manually done it so far and pushed it local repo until @rschreijer gets it done.

**Comment by nielssj** [comment]
+1

**Comment by esetnik** [comment]
Has this been abandoned? We should fork it and create a solid Java wrapper for Mandrill.

**Comment by billoneil** [comment]
@eweatherley This is an old PR but can you remove all the files except ```MandrillMessage.java``` from the PR?  I don't think any of the other files are needed for this PR.

**Comment by billoneil** [comment]
Relevant commit cherry picked to master https://github.com/rschreijer/lutung/commit/293627b9e0c81a4704922bca8f2b9f700d848152

**Pull request closed without merging**
